### PR TITLE
App form better mobile

### PR DESCRIPTION
**Pull request by kailanjian**
## Proposed changes
Increase conversion rate for mobile through some ui improvements.

## Types of changes

- [x] I've labeled this PR with appropriate labels (`comp/*` component, bug/feature, documentation and other less important ones).

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] fixes for this https://3.basecamp.com/4474129/buckets/16836016/todos/2960890991#__recording_2964642453
- [x] was not able to replicate button issue but my changes should fix it.
- [x] accessibility is reduced because button links are semantically links now instead of buttons, but I think we don't care about that too much.
- [x] would appreciate if someone could do a quick smoke test in addition to looking at the code to reduce risk of breaking something on the application page.

### CODE REVIEW

**Comment by JonSEng** [comment]
Hey @kailanjian thanks for working on this. How would one test this locally? Did you find a good way to test it?

**Comment by kailanjian** [comment]
you don't need a big test, it's just ui changes so as long as it runs on your or someone elses machine and looks ok with different window sizes and you can submit without a network error it should be good.

**Review by JonSEng — APPROVED** [review]
It looks good on mobile.

I tested it out using ngrok to port forward my local to the public internet.

```
ngrok by @inconshreveable                                                                                                                                                                   (Ctrl+C to quit)

Session Status                online
Session Expires               7 hours, 58 minutes
Version                       2.3.35
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://0083410ba5c0.ngrok.io -> http://localhost:8080
Forwarding                    https://0083410ba5c0.ngrok.io -> http://localhost:8080
```

IMG_2688
IMG_2687
IMG_2686
IMG_2685
IMG_2684

**Comment by kailanjian** [comment]
Cool, thanks!

**Pull request merged**
