### PR TITLE
Remove fields 

### PR DESCRIPTION
**Pull request by kailanjian**
closes https://github.com/International-Mentorship-ISMP/ismp/issues/150

### CODE REVIEW

**Comment by kailanjian** [comment]
https://github.com/International-Mentorship-ISMP/ismp/pull/207 needs to be merged first

**Comment by douglaschan32167** [comment]
@kailanjian Just merged 207. Can you rebase this onto it?

**Comment by kailanjian** [comment]
yup thanks, just fyi though this is failing tests rn so need to fix

**Comment by kailanjian** [comment]
@douglaschan32167 rebased! ready for code review

**Pull request merged**
