### PR TITLE
Header/Footer: Social Media Icons

### LINKED ISSUE #132: Header/Footer: Social Media Icons
Get the new social media icons and add them to the footer and header according to the design
https://www.figma.com/file/k6TNqd4V49TsJlsvaZKnQV/International-Student-Mentorship-Program?node-id=153%3A603

Please also link to our wechat (QR code not in scope for V1). Ask Dustin Chen for the WeChat link

### PR DESCRIPTION
**Pull request by vickyadebona**
## Proposed changes
- Added links to social media icons in the header
- Added links to social media icons in the footer
- Added LinkedIn icon to header and footer with their links
- Made social media icons in footer match Figma
- Some NavBar clean up

## Types of changes

- [x] I've labeled this PR with appropriate labels (`comp/*` component, bug/feature, documentation and other less important ones).

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] I've linked the proper Github Issue(s) to my PR
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests (unit, integration...etc.) that prove my fix is effective or that my change works
- [x] I have added or updated necessary documentation (if appropriate). You can search, for instance using the [`silver searcher`](https://github.com/ggreer/the_silver_searcher) `ag <STRING>` to find all usages in the repository.
- [x] I have notified the team of any breaking or important changes

closes #132

### CODE REVIEW

**Comment by iksoosong** [comment]
The header content looks like it isn't lined up with the body + footer content anymore. Is that what we want?

**Comment by vickyadebona** [comment]
@iksoosong I changed it because it otherwise looked really squished with all of the stuff that we have on the navbar, and then it also wasn't centered on certain screen sizes. Let me know if this is an issue and I can revert it :)

**Comment by iksoosong** [comment]
Ah. another solution could be to make the breakpoint for the nav different, so that it goes into the collapsed view sooner. 
@lillyglin can make the call, but imo, it looks better to have the content of the header in a container.

**Comment by vickyadebona** [comment]
@richyen @iksoosong it's ready to be looked at again :)

**Comment by douglaschan32167** [comment]
Just one more thing: now that you're using S3, can you remove the social media icon pngs from the PR? Otherwise, LGTM

**Comment by vickyadebona** [comment]
@douglaschan32167 the icons are now deleted from the local images folder and are no longer imported in the code :)

**Comment by douglaschan32167** [comment]
I think Rich Yen won't be able to revise his changes requested anytime soon, so I'll probably push this pr through in a bit

**Pull request merged**
