### PR TITLE
Application form handle backend errors

### PR DESCRIPTION
**Pull request by kailanjian**
## Proposed changes
Fixes date validation to make it impossible to submit a value (through frontend validations) that backend won't be able to handle.
Little bit of cleanup to add space on top of page.
Add warning message if something goes bad while submitting.

## Types of changes

- [x] I've labeled this PR with appropriate labels (`comp/*` component, bug/feature, documentation and other less important ones).

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] I've linked the proper Github Issue(s) to my PR
- [x] I have added or updated necessary documentation (if appropriate). You can search, for instance using the [`silver searcher`](https://github.com/ggreer/the_silver_searcher) `ag <STRING>` to find all usages in the repository. - No documentation
- [x] I have notified the team of any breaking or important changes - nothing major
I think my linter is broken, not sure how important that is, also no frontend tests yet so no tests added.
----
- closes https://github.com/International-Mentorship-ISMP/ismp/issues/123
- instead of toast, I opted for just a little popup message since semantic doesn't have toasts
- it should not be possible to submit invalid data through frontend (without triggering validations that won't let you submit), so this should only occur on a network failure or someone tampering with the network request.
  - made it so date has to be between 1000-2999 and backend checks for 1000-9999
  - fields all have maxLength of 100 or 1000 which is the only validation for the rest of the fields
- can test by taking down backend and submitting and seeing that it just gracefully pops up the little error message.

### CODE REVIEW

**Comment by kailanjian** [comment]
Error message:
image

Some general page style changes:
image

**Comment by douglaschan32167** [comment]
@kailanjian  For some reason it lets me add birth year 0000 and doesn't complain until it tries hitting the backend. I'm not seeing the error message either; I had to open up the console to see it.

**Comment by jessewoo** [comment]
lgtm.

**Comment by jessewoo** [comment]
@kailanjian - squash and merge?

**Pull request merged**
