### PR TITLE
Update `eslint` pre-commit hook to not allow any warnings.

### PR DESCRIPTION
**Pull request by dbtung**
## Proposed changes
The default eslint rules defined by `create-react-app` are actually pretty lenient (see https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.js) so make it more strict by not allowing any warnings.

This change will make it so that the pre-commit checks fail if any files that the developer changes has eslint warnings.
## Types of changes

- [ ] I've labeled this PR with appropriate labels (`comp/*` component, bug/feature, documentation and other less important ones).

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] I've linked the proper Github Issue(s) to my PR
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests (unit, integration...etc.) that prove my fix is effective or that my change works
- [x] I have added or updated necessary documentation (if appropriate). You can search, for instance using the [`silver searcher`](https://github.com/ggreer/the_silver_searcher) `ag <STRING>` to find all usages in the repository.
- [x] I have notified the team of any breaking or important changes

### CODE REVIEW

**Comment by iksoosong** [comment]
do we have to do something to get this to work on our local machines? I tried committing with a typo and it didn't seem to block that

**Comment by dbtung** [comment]
> do we have to do something to get this to work on our local machines? I tried committing with a typo and it didn't seem to block that

Hmmm, not that I know. It should just work. What kind of typo did you try?

**Comment by iksoosong** [comment]
> > do we have to do something to get this to work on our local machines? I tried committing with a typo and it didn't seem to block that
> 
> Hmmm, not that I know. It should just work. What kind of typo did you try?

I deleted a letter in `useTranslation` import in the `Mentors.jsx` file to be `useTranslaton`. It complains properly in the `make up` output, but the commits seem unaffected

**Comment by dbtung** [comment]
Hmmm, weird. This is what I had. I made this change in the source:

Screen Shot 2020-07-04 at 5 20 51 PM

And this is what happened when I tried to commit:

Screen Shot 2020-07-04 at 5 21 03 PM

**Comment by dbtung** [comment]
@iksoosong Is there anything in your `.git/hooks` directory - specifically a `.git/hooks/pre-commit` file that references `husky`?

**Comment by iksoosong** [comment]
I have a `husky.local.sh` and `husky.sh` in there. Nothing that combines `pre-commit` and `husky` in the file name though.

**Comment by dbtung** [comment]
Contents of my `pre-commit` file is:

`#!/bin/sh`
`# husky`

`# Created by Husky v4.2.5 (https://github.com/typicode/husky#readme)`
`#   At: 7/2/2020, 8:23:51 PM`
`#   From: /Users/david.tung/personal/ismp/frontend/node_modules/husky (https://github.com/typicode/husky#readme)`

`. "$(dirname "$0")/husky.sh"`

If that's what it looks like, what happens when you call `bash .git/hooks/pre-commit` from the projector root?

**Comment by iksoosong** [comment]
hm, maybe it's just my environment got messed up. i'm trying to kill my containers and reclone the repo to a fresh state but looks like docker is having trouble stopping some containers. Maybe @douglaschan32167 can try.

**Comment by iksoosong** [comment]
Restarting from scratch and running `yarn` in `frontend/` seems to have made this work. Thanks! Wonder if we can get this to work without any user intervention. but that can be for another time.

**Pull request merged**
