### PR TITLE
404 Page

### PR DESCRIPTION
**Pull request by iksoosong**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
Added a 404 page

It's not great, but better than not having one. 

Screen Shot 2020-07-01 at 10 09 54 PM

### CODE REVIEW

**Comment by douglaschan32167** [comment]
Not sure how I feel about this interaction with the blog not found page. 
image

**Comment by iksoosong** [comment]
> Not sure how I feel about this interaction with the blog not found page.
> image

Ah, good catch. Let me fix that.

**Comment by iksoosong** [comment]
@douglaschan32167 the issue was with the switch statement. It wasn't working right. Can you try again? My blogs page isn't working :(

**Comment by iksoosong** [comment]
looks like it works now

**Pull request merged**
