### PR TITLE
Application form add chinese translations

### LINKED ISSUE #300: Application Form - Add Chinese Translation
using
- https://docs.google.com/document/d/1ssRT47aA0BVtNZLXf0IzQw3khM4plsA6JzdD6xiY3EM/edit
- https://3.basecamp.com/4474129/buckets/16925967/documents/2746721319
- https://3.basecamp.com/4474129/buckets/16925967/todos/2797482610#__recording_2798496590

### PR DESCRIPTION
**Pull request by kailanjian**
## Proposed changes
Put in Chinese translations for application form based on:
https://3.basecamp.com/4474129/buckets/16925967/todos/2797482610#__recording_2798496590

## Types of changes

- [x] I've labeled this PR with appropriate labels (`comp/*` component, bug/feature, documentation and other less important ones).

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] I've linked the proper Github Issue(s) to my PR
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests (unit, integration...etc.) that prove my fix is effective or that my change works
- [x] I have added or updated necessary documentation (if appropriate). You can search, for instance using the [`silver searcher`](https://github.com/ggreer/the_silver_searcher) `ag <STRING>` to find all usages in the repository.
- [x] I have notified the team of any breaking or important changes

---
closes #300

### CODE REVIEW

**Comment by kailanjian** [comment]
this may conflict with https://github.com/International-Mentorship-ISMP/ismp/pull/323 so just let me know and I can rebase after one is merged

**Comment by kailanjian** [comment]
@douglaschan32167 just force pushed a fix + rebase placeholder is showing up fine in my revision but I fixed the terms and other links being in english

**Comment by douglaschan32167** [comment]
Can you add ApplicationForm.jsx into this too? It looks like it's missing a t( )
          {inputs['other'] && (
            <Form.Field
              fluid
              id="form-input-control-other-topic"
              control={Input}
              label={t('fields.other_topic.label')}
              **placeholder={'fields.other_topic.placeholder'}**
              name="other_topic"
              type="text"
              maxLength="100"
              onChange={handleInputChange}
              value={inputs.other_topic}
            />
          )}

**Comment by kailanjian** [comment]
@douglaschan32167 my bad, I just realized you were talking about the other field which I didn't check. Thank you so much for checking! the change is pushed in a new commit.

**Pull request merged**
